spring.application.name=05_Rest_Api_Demo_Employee

spring.datasource.url=jdbc:mysql://localhost:3306/employee_rest_demo
spring.datasource.username=root
spring.datasource.password=cmk26@2004

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true